site_name: Documentation Géomatique
site_description: Plateforme de documentation en géomatique
site_author: Chafii Abdi Ahmed

theme:
  name: material
  language: fr
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy

nav:
  - Accueil: index.md

  - Contexte: contexte.md

  - Gestion de projet:
      - Type de gestion de projet: gestion-projet/type-gestion.md
      - Périmètres du projet: gestion-projet/perimetres.md
      - Répartition des tâches: gestion-projet/repartition-taches.md
      - Risques: gestion-projet/risques.md
      - Gouvernance: gestion-projet/gouvernance.md

  - Base de données:
      - Introduction de la base de données: base-donnees/introduction.md
      - Admin BDD & PgSQL: base-donnees/admin-bdd-pgsql.md
      - PostGIS: base-donnees/postgis.md

  - Contrôle qualité des données:
      - ISO 19115: controle-qualite/iso-19115.md
      - Aspect juridique: controle-qualite/aspect-juridique.md

  - Formats ESRI: formats-esri.md

  - Télédétection:
      - Introduction de la télédétection: teledetection/introduction.md
      - Télédétection optique: teledetection/optique.md
      - Télédétection LiDAR: teledetection/lidar.md
      - Télédétection Radar: teledetection/radar.md

  - Python & PyQGIS:
      - Introduction de Python: python-pyqgis/introduction-python.md
      - PyQGIS: python-pyqgis/pyqgis.md

  - Données & Interopérabilité:
      - VRT: donnees-interoperabilite/vrt.md
      - Droit des données: donnees-interoperabilite/droit-donnees.md
      - Cycle de données: donnees-interoperabilite/cycle-donnees.md
      - Métadonnées: donnees-interoperabilite/metadonnees.md