title: Documentation CPGEOM
description: Chef de projet géomatique
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

search_enabled: true

aux_links:
  "Voir le dépôt GitHub":
    - "https://github.com/chafiiabdi/cpgeom-chefdeprojetgeomatique"

color_scheme: light