site_name: Plateforme de documentation en Géomatique
site_description: Documentation CPGEOM pour les cours et ressources de géomatique
site_author: Chafii Abdi Ahmed
site_url: https://chafiiabdi.github.io/cpgeom-chefdeprojetgeomatique/

docs_dir: source
site_dir: docs
use_directory_urls: false

theme:
  name: rtd-dropdown
  locale: fr
  highlightjs: true
  hljs_languages:
    - sql
    - python
    - bash

nav:
  - Contexte: index.md
  - Gestion de projet:
      - Vue d'ensemble: gestion-projet.md
      - Type de gestion de projet: gestion-type.md
      - Périmètres du projet: gestion-perimetres.md
      - Répartition des tâches: gestion-repartition-taches.md
      - Risques: gestion-risques.md
      - Gouvernance: gestion-gouvernance.md
  - Base de données:
      - Vue d'ensemble: base-donnees.md
      - Introduction de la base de données: bdd-introduction.md
      - Admin BDD & PgSQL: bdd-admin-pgsql.md
      - PostGIS: bdd-postgis.md
  - Contrôle qualité des données:
      - Vue d'ensemble: controle-qualite-donnees.md
      - ISO 19115: cq-iso-19115.md
      - Aspect juridique: cq-aspect-juridique.md
  - Formats ESRI: formats-esri.md
  - Télédétection:
      - Vue d'ensemble: teledetection.md
      - Introduction de la télédétection: teledetection-introduction.md
      - Télédétection optique: teledetection-optique.md
      - Télédétection LiDAR: teledetection-lidar.md
      - Télédétection Radar: teledetection-radar.md
  - Python & PyQGIS:
      - Vue d'ensemble: python-pyqgis.md
      - Introduction de Python: python-introduction.md
      - PyQGIS: pyqgis.md
  - Données & Interopérabilité:
      - Vue d'ensemble: donnees-interoperabilite.md
      - VRT: donnees-vrt.md
      - Droit de données: donnees-droit.md
      - Cycle de données: donnees-cycle.md
      - Métadonnées: donnees-metadonnees.md
  - Modifier le site: modifier.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - attr_list

extra_css:
  - stylesheets/cpgeom.css
